### ISSUE TITLE
How to get my own input files ?

### ISSUE THREAD

**Issue by wyj-lzu** [NovembreLab/feems#1]
Hi!

Thanks for a nice feems!

I run test data successfully. But how to prepare my own data file such as grid_100.shp, grid_100.shx and wolvesadmix* ?

Best.

**Comment by wyj-lzu** [comment]
I think .bed .fam .bim files were from PLINK

I don't know how to prepare grid_100* files ?

**Comment by wyj-lzu** [comment]
OK, it seems that I got the input files.  But I got the new error : 

Traceback (most recent call last):
  File "newtest.py", line 37, in <module>
    outer, edges, grid, _ = prepare_graph_inputs(coord=coord,
  File "/home/ug0134/feems/feems/utils.py", line 99, in prepare_graph_inputs
    pts, rev_pts, e = create_tile_dict(tiles3, bpoly)
  File "/home/ug0134/feems/feems/utils.py", line 32, in create_tile_dict
    x, y = poly.exterior.xy
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

How can i fixed it ? Thanks !

**Comment by jnovembre** [comment]
Glad you found the prepare_graph_inputs function.  I think the error your seeing is a sign that something is awry with the coords or outer point lists you're passing in.  Double check your coords sit nicely inside the polygon described by outer?
