### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by bernt-matthias** [NovembreLab/feems#12]
Would it be possible to create a release/release tag of feems? If so I could try to create a conda recipe for the software (e.g. at bioconda). 

Users at my institution struggle with the installation and I guess that it would be more convenient if installation could be managed completely by conda.

**Comment by pcarbo** [comment]
@bernt-matthias Thanks! I've created [a release for feems 1.0.0](https://github.com/NovembreLab/feems/releases/tag/v1.0.0). Please let us know when you have created a conda recipe and we will update the README with this information.

**Comment by bernt-matthias** [comment]
Thanks for the fast reply. I opened a PR here https://github.com/bioconda/bioconda-recipes/pull/34717. Comments are welcome: 

- do you agree with unpinning the minor versions of the requirements (makes it easier for the conda resolver)
- do you want to be added to the maintainers? Then you get an email on auto updates

**Comment by bernt-matthias** [comment]
I would also suggest to remove jupyter from the bioconda recipe because its not really needed to use the library. You may still add it in the installation...

**Comment by bernt-matthias** [comment]
Closing this. Thanks a lot for the help. 

Just for completeness: If you create a new release over here then bioconda will automatically update the recipe.

**Comment by pcarbo** [comment]
Thanks @bernt-matthias! Regarding your earlier questions, please go ahead and do what you think is best. I don't think we have much experience with bioconda. And no need to add us as maintainers.

If you could please let us know when when feems is available on bioconda and we would be happy to test it out. Thanks again.

**Comment by bernt-matthias** [comment]
The bioconda package and biocontainer should now be available.

**Comment by pcarbo** [comment]
@bernt-matthias Thanks! This is perhaps because I'm not using the most recent Anaconda3 distribution, but I get the following error:

```
$ conda --version
conda 4.10.3
$ conda install -c bioconda feems
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
ResolvePackageNotFound:
  - suitesparse=5.7
```

**Comment by bernt-matthias** [comment]
You probably just need to add `-c conda-forge`

**Comment by pcarbo** [comment]
And, thanks, I've updated the installation instructions in the README.

**Comment by pcarbo** [comment]
Okay, thanks for clarifying.
