### ISSUE TITLE
Plotting boundary issue: grid not extending across the North Atlantic

### ISSUE THREAD

**Issue by GoodallJake** [NovembreLab/feems#16]
Hello, I was wondering if you might be able to provide some feedback on an issue I'm having. I'm trying to plot data across the North Atlantic with individuals located in both the east coast of Canada/ Greenland and in Europe. I keep on hitting a plotting boundary in the North Atlantic (around 40 degrees longitude), roughly at the centre of Greenland. 

This is best illustrated with some figures (see attached). Essentially I can plot the Canadian/Greenland samples but the grid doesn't extend across to Europe, or I can plot the European samples and the grid will not extend over to the America's. Note that in the attached examples I changed the resolution of the grid as I was optimising, but this isn't the issue. The issue is that there seems to be a plotting boundary that the grid simply will not pass. 

Do you have any ideas about what is causing this? I've had someone replicate this independently and they too have issues with the Greenland boundary point. How can I get my grid to extend across the entire North Atlantic range?

Kind Regards,
Jake

![Figure 2023-01-19 161648 (31)](https://user-images.githubusercontent.com/118358330/213707812-691bcab8-d83c-433d-893e-6010dc33b36b.png)
![Figure 2023-01-19 161648 (34)](https://user-images.githubusercontent.com/118358330/213707823-d3e922bc-3e10-4cb0-b247-f87a7e4a3775.png)

**Comment by karolisr** [comment]
Hi, I just encountered the same issue. I figured out a fix. There is a function called `wrap_america` in the file `utils.py`:
https://github.com/NovembreLab/feems/blob/c08a179a46bc24ac1f49d7f4b1dd1e1b74b00962/feems/utils.py#L18

I tried hard to figure out what it could be for but could not understand it. Comment the entire function out. Then go to:
https://github.com/NovembreLab/feems/blob/c08a179a46bc24ac1f49d7f4b1dd1e1b74b00962/feems/utils.py#L33
and change it to `points = tuple(zip(np.round(x, 3), np.round(y, 3)))`

comment out:
https://github.com/NovembreLab/feems/blob/c08a179a46bc24ac1f49d7f4b1dd1e1b74b00962/feems/utils.py#L34

That's it. You may have to set `translated=True` in your `prepare_graph_inputs` call.

**Comment by VivaswatS** [comment]
Thanks @karolisr, this function is supposed to wrap around the Americas (useful if you want to look at Africa, Eurasia & Australia in a single map), but we've never encountered a use-case with samples in the Atlantic yet! 

Yes, commenting it out would be the way to go @GoodallJake
