### ISSUE TITLE
Graph fit not converging

### ISSUE THREAD

**Issue by twooldridge** [NovembreLab/feems#19]
Hello,

Thank you for developing this software! I'm attempting to infer boundaries to migration in a coastal intertidal species, and unfortunately I keep running into an error in the final estimation step with `sp_graph.fit`. Essentially, I keep getting the following error:

AssertionError: did not converge

I've tried to see if different values of `lambda` matter, and I've raised `maxiter`, but I reliably get the same issue every time. I've attached the data necessary to rerun the code. It's a 'toy' dataset of 35 unique individuals and ~ 8000 SNPs. Here's what I've done so far by following the workshop.ipynb notebook:

Reading genotype data and imputing missing data:
```
(bim, fam, G) = read_plink('./feems/chr1_highcov')
imp = SimpleImputer(missing_values=np.nan, strategy="mean")
genotypes = imp.fit_transform((np.array(G)).T)
print("n_samples={}, n_snps={}".format(genotypes.shape[0], genotypes.shape[1]))
```

Creating the graph input:
```
# sample coordinates file
coord = np.loadtxt("./feems/chr1_highcov.coords")
# Outer polygon
outer = np.loadtxt("./feems/input.outer")  # outer coordinates, doesn't change regardless of input data
# Grid path
grid_path = "./feems/cropped_grid.shp" # path to denser discrete global grid
# graph input files
outer, edges, grid, _ = prepare_graph_inputs(coord=coord, 
                                             ggrid=grid_path,
                                             translated=True, 
                                             buffer=0,
                                             outer=outer)
```

Setting up spatialgraph object
```
%%time
sp_graph = SpatialGraph(genotypes, coord, grid, edges, scale_snps=True)
```

Visualizing the grid:
```
projection = ccrs.EquidistantConic(central_longitude=-121.938552, central_latitude=36.62950099)
fig = plt.figure(dpi=300)
ax = fig.add_subplot(1, 1, 1, projection=projection)  
v = Viz(ax, sp_graph, projection=projection, edge_width=.5, 
        edge_alpha=1, sample_pt_size=10, edge_zorder=100,
        obs_node_size=7.5, sample_pt_color="black", 
        cbar_font_size=10)
v.draw_map()
v.draw_samples()
v.draw_edges(use_weights=False)
v.draw_obs_nodes(use_ids=False)
```
![image](https://github.com/NovembreLab/feems/assets/16786856/e779797b-96c3-4f7e-988e-4d68d6fbb571)

And finally, running fit (this is where it fail every time):
```
%%time
sp_graph.fit(lamb=40.0)
```

Do you have any suggestions for how to troubleshoot this? I have a sneaking suspicion this is due to the odd distribution of samples I have given the ecological niche, but I'm not sure what to do about that. Thanks in advance for your help, and let me know if I can clarify anything!

Best,
Brock
[brock_feems.tar.gz](https://github.com/NovembreLab/feems/files/11853381/brock_feems.tar.gz)

**Comment by jkreinz** [comment]
I resolved the same issue by removing monomorphic sites.

**Comment by VivaswatS** [comment]
Thanks @jkreinz, FEEMS only works with segregating sites so please ensure to remove invariant sites. Hope that resolves the issue—please reopen if not
