### ISSUE TITLE
Exporting spatial graph to a .shp file?

### ISSUE THREAD

**Issue by squisquater** [NovembreLab/feems#26]
I was wondering whether anyone had tried exporting the spatial graphs to shapefiles?

I was able to successfully run feems by creating a feems conda environment using the instructions outlined in a [previous issue](https://github.com/NovembreLab/feems/issues/15#issuecomment-1496502029). This involved using the feems.txt file to recreate the environment and the following code: 
```
conda create --name feems2 --file feems.txt
# Then clone or download feems from GitHub.
cd feems
pip install .
```
I am wondering whether there is any internal functionality within feems to export the resulting spatial_graph object to a shapefile. I thought I may be able to do this with geopandas but I can't install it to my feems conda environment without breaking the functionality of feems. I also tried pickling the spatial graph to my output directory and 'unpiclking' or re-uploading it in a geopandas specific conda environment -- but it won't unpickle without feems also installed.

**Comment by VivaswatS** [comment]
Hmm, we don't quite have public functionality for this just yet. The spatial graph object is quite complex as it contains many different attributes like node positions, edge weights, parameter estimates, etc., so I don't think it can be easily exported to a shapefile. You can view all these attributes by running: 
`sp_graph.__dict__.keys()`
Output:
`dict_keys(['graph', '_node', '_adj', 'nodes', 'sample_pos', 'node_pos', 'scale_snps', 'edges', 'Delta_q', 'adj', 'adj_base', 'nnz_idx', 'degree', 'Delta', 'diag_oper', 'n_observed_nodes', 'assned_node_idx', 'n_samples_per_obs_node_permuted', 'nnz_idx_perm', 'adj_perm', 'P', 'factor', 'w', 'B', 'genotypes', 'n_snps', 'frequencies', 'mu', 's2', 'q', 'q_diag', 'q_inv_diag', 'q_inv_grad', 'S', 'lre', 'c', 'option', 'W', 'D', 'L', 'L_block', 'w0', 'train_loss'])`

Here is some preliminary code that you can use to extract the relevant attributes from the spatial graph object in python to a csv file and then to create a shapefile out of it in R (using package `sf`):
````
# in python
# write the deme coordinates + sample size (node attributes) out into a csv file
np.savetxt('nodepos.csv', np.vstack((sp_graph.node_pos.T, [sp_graph.nodes[n]['n_samples'] for n in range(len(sp_graph.nodes))])).T, delimiter=',') 
# write the relevant edge weights out into a csv file
np.savetxt('edgew.csv', np.vstack((np.array(sp_graph.edges).T, sp_graph.w)).T, delimiter=',')
````

````
# in R
library(sf)
library(data.table)
library(mutate)
prepare_data <- function(edge_file, node_file){
    edges <- fread(edge_file, col.names = c("from_id", "to_id", "edge_weight"))
    nodes <- fread(node_file, col.names = c("Longitude", "Latitude","N")) %>% mutate(V1 = row_number() - 1)
    
    # Convert necessary columns to integer
    edges$from_id <- as.integer(edges$from_id)
    edges$to_id <- as.integer(edges$to_id)
    nodes$V1 <- as.integer(nodes$V1)
    
    # Join edges and nodes data to get the start and end points of each edge
    edges <- edges %>%
        left_join(nodes, by = c("from_id" = "V1")) %>%
        left_join(nodes, by = c("to_id" = "V1"), suffix = c(".from", ".to")) %>%
        mutate(weight = log10(edge_weight)-mean(log10(edge_weight)))
    
    #print(edges$weight)
    
    # Create a list of linestrings, each defined by a pair of points
    edges$geometry <- mapply(function(lon_from, lat_from, lon_to, lat_to) {
        st_linestring(rbind(c(lon_from, lat_from), c(lon_to, lat_to)))
    }, edges$Longitude.from, edges$Latitude.from, edges$Longitude.to, edges$Latitude.to, SIMPLIFY = FALSE)
    
    # Convert edges to an sf object
    edges_sf <- st_as_sf(edges)
    
    # Set the CRS
    st_crs(edges_sf) <- 4326
    
    # Convert nodes data.table to an sf object
    nodes_sf <- st_as_sf(nodes, coords = c("Longitude", "Latitude"), crs = 4326)
    
    list(edges_sf = edges_sf, nodes_sf = nodes_sf)
}
data <- prepare_data('edgew.csv', 'nodepos.csv')
````

Let me know if you have any other questions.

**Comment by squisquater** [comment]
That worked great thanks! One thing possibly worth noting is that I believe the mutate function comes from the dplyr package not the mutate package so this script only worked for me when swapping library(dplyr) out for library(mutate).

I then did the following after running the above script to export the sf objects to shape files.

```
# Export edges_sf to shapefile
st_write(data$edges_sf, "path_to_save_edges/edges_shapefile.shp")

# Export nodes_sf to shapefile
st_write(data$nodes_sf, "path_to_save_nodes/nodes_shapefile.shp")
```
