### ISSUE TITLE
Can feems be applied to a small region?

### ISSUE THREAD

**Issue by labdlw** [NovembreLab/feems#33]
Dear FEEMS authors and users,

Thank you for developing this software. I have a few issues running this script on my data. I have 252 individuals spread across just 50 km of maximum distance and 12k SNPs. I have filtered invariant sites from the vcf files before applying plink. 

When I try this dataset on the provided with the grid_100.shp I have the "Assertion error : grid is empty changing translation". But, when I run it with a grid generated from ddgridR (res8) I get the following results ; with just 3 nodes and 2 links. I'm not sure why it looks like this.
![feems_op_res8](https://github.com/NovembreLab/feems/assets/160532925/363d3d6c-2d1b-4121-b197-9faaab1b8ff0)

It would be nice to have a triangular grid span over this small area of just 50km. Is that even possible? some genotypes are only 2 or 3 meters apart. 

I tried generating a 50meters square grid that has the exact layer delimitation as the outer coordinates and it works until the prepare_graph_inputs command but then later on I get this error "IndexError: index 340932 is out of bounds for axis 0 with size 340932".
![Screenshot from 2024-02-19 20-01-55](https://github.com/NovembreLab/feems/assets/160532925/4f8c8ba1-451e-48db-99a8-a010d657bb38)

I would appreciate any advice and insights.
Cheers
Lina

**Comment by VivaswatS** [comment]
Hi @labdlw, using `ddgridR` is the right idea! Have you tried using a `res=10` (higher values indicate smaller grids)? Maybe this will be the right scale.

**Comment by karolisr** [comment]
@labdlw Check out the script I used in a recent study: [generate-dgg-files.R](https://github.com/karolisr/pitcairnia-dr-nrv/blob/36430941db8762b703ef58d94764b77a33763798/data/dggs/generate-dgg-files.R)
