### ISSUE TITLE
Issues with adjusting graph size

### ISSUE THREAD

**Issue by jackslinde35** [NovembreLab/feems#34]
Hello,

I have tried implementing this software for a population genomics dataset of mine. I am having issues with graphing and I can't seem to find a way to adjust the graph scope to show more of the map for context - this is a in North America north of Mexico. I also wonder if it is possible to add in state lines to the graph? 

Anyway, here is the pdf I get by the end of the process which I would like to be able to customize a bit more. Any suggestions on this?

Best,

Jackson
[myImagePDF.pdf](https://github.com/NovembreLab/feems/files/14563737/myImagePDF.pdf)

**Comment by karolisr** [comment]
Hi,
I had a similar issue recently. I ended up exporting FEEMS grid into CSV tables ([code](https://github.com/karolisr/pitcairnia-dr-nrv/blob/93534b6906d2a59a821c19deaef649eb1a3fb283/31-feems/31-feems-run.py#L196
)) and reconstructing them in [R](https://github.com/karolisr/pitcairnia-dr-nrv/blob/93534b6906d2a59a821c19deaef649eb1a3fb283/25-geo-dist.R#L53) where I could graph it with more flexibility.

End result: [feems-fig.pdf](https://github.com/NovembreLab/feems/files/14610347/feems-fig.pdf)

Hope this is somewhat helpful.

**Comment by jackslinde35** [comment]
Fantastic! I will check it out soon. This looks very helpful.

Thank you!

**Comment by Dahn-YoungDong** [comment]
@karolisr Could you expalin how your code solve the sub-continental boundaries such as country boundary and state boundary? Also @jackslinde35 were you able to resolve this issue on your own? If so, how?

**Comment by karolisr** [comment]
> @karolisr Could you expalin how your code solve the sub-continental boundaries such as country boundary and state boundary? Also @jackslinde35 were you able to resolve this issue on your own? If so, how?

Simple answer is R, I exported the results as CSV files and reimported them in R. I am more familiar with maps in R. Then I just plotted the map as I wanted in R and overlayed the FEEMS grid over it.

**Comment by Dahn-YoungDong** [comment]
> > @karolisr Could you expalin how your code solve the sub-continental boundaries such as country boundary and state boundary? Also @jackslinde35 were you able to resolve this issue on your own? If so, how?
> 
> Simple answer is R, I exported the results as CSV files and reimported them in R. I am more familiar with maps in R. Then I just plotted the map as I wanted in R and overlayed the FEEMS grid over it.

Thanks!!

**Comment by Dahn-YoungDong** [comment]
I ended up exporting the Viz grid output as shapefile and visualized it in ArcGis

**Comment by VivaswatS** [comment]
Closing this for now, please re-open if you have any more issues
