### ISSUE TITLE
Modify viz.py to visualize sub-country boundaries?

### ISSUE THREAD

**Issue by Dahn-YoungDong** [NovembreLab/feems#36]
Dear authors and community,

I work with regional samples, and based on the getting_started file I was only able to generate a gray underlying map. When I looked into how viz.py plots the map, it only visualizes the continental coastline, and not visualizing additional levels of geo-boundaries such as nation and states, and counties.

What would be a good and fairly easy solution to overlay a country-state-county map to a grid analysis of a smaller region? So that the geographical background is rendered more interpretable?

Best,
Dahn-young

**Comment by VivaswatS** [comment]
Hi @Dahn-YoungDong, that's a good question! 

Easiest way would be to first import the right package:
`import cartopy.feature as cfeature`

Then, you could just add a single line under you code where you've initialized and plotted your Viz object (i.e., FEEMS map): 
`v.ax.add_feature(cfeature.BORDERS, color='grey', linestyle='--', zorder=0)`

This will add country borders to your underlying map. You can add other features in a similar fashion, see https://scitools.org.uk/cartopy/docs/latest/reference/feature.html for options. 

P.S. I could only add state boundaries for the USA using `cfeature.STATES`, so this might need a little bit more tweaking

**Comment by VivaswatS** [comment]
Ah, a quick ChatGPT prompt gave me a fairly simple option for states in other countries:
`v.ax.add_feature(cfeature.NaturalEarthFeature(category='cultural', name='admin_1_states_provinces_lines', scale='50m', linestyle='--', edgecolor='k', facecolor='white'), zorder=0)`

**Comment by Dahn-YoungDong** [comment]
Thank you!

Dahn-young (Young) Dong [image: A button with "Hear my name" text for name
playback in email signature]  <https://www.name-coach.com/danyang-dong>
